### ISSUE TITLE
Add PORT config field

### ISSUE THREAD

**Issue by vyscond** [dingjie/atom-sync#34]
I would like to connect through 2200 as this is the most common routing used with virtualboxes to "reverse proxy" connection from the host machine :)

**Comment by dingjie** [comment]
Update to 0.7.3 and set option.shell to "ssh -p 2200"

![qq20160417-0 2x](https://cloud.githubusercontent.com/assets/586262/14585900/453483b2-04b9-11e6-97de-87a2dac0cdfa.png)

**Comment by jeffwidman** [comment]
Isn't this a feature better handled by modifying `~.ssh/config` to set the default port for a particular connection or alias? I'd hate to see this plugin start re-inventing the SSH config file.

**Comment by dingjie** [comment]
@jeffwidman yes, I agree, all ssh config should be stored in ssh_config. That's why I'm still using ssh/rsync command instead of [ssh2 module from npm](https://www.npmjs.com/package/ssh2).

This parameter is [extracted from existing rsync command](https://github.com/dingjie/atom-sync/commit/0d9158a528077fe61d712d0d534dd9a07ebb25c6) (lib/service/rsync-service.coffee line:35) in order to specify the location of ssh command which is not in path, of course, users can thereby set ssh port, key file even cleartext password in this field on their own risk.

Don't worry about putting all ssh config into .sync-config.cson in the future version which is not going to happen.
